#include <iostream>

#include "Compiler.hpp"
#include "Error.hpp"
#include "Lexer.hpp"
#include "Parser.hpp"
#include "Util.hpp"
#include "VM.hpp"

int main() {
    std::string testSourceCode =
        "if 0 { emitln(\"True!!!\") } else emitln(\"False!!!\")";

    try {
        EigerC::Lexer lex(testSourceCode);
        EigerC::Parser parser(lex);

        EigerC::CompilerContext ctx;

        EigerC::BytecodeCompiler compiler(parser.Parse(), ctx);
        compiler.DoCodegen();

        std::cout << "==== Generated Bytecode ====" << std::endl;
        for (const EigerC::Instruction& inst : compiler.GetInstructions())
            inst.PrettyPrint();
        std::cout << "====                    ====" << std::endl;

        std::cout << "====      VM Result     ====" << std::endl;

        EigerC::BytecodeVM vm(compiler, ctx);

        vm.ExecuteBytecode();

    } catch (EigerC::Error& e) {
        std::cerr << EigerC::Util::ErrorTypeToString(e.GetType()) << ": "
                  << e.GetMessage() << " at line " << e.GetLine() << std::endl;
        return 1;
    } catch (const std::exception& e) {
        std::cerr << "Unexpected error: " << e.what() << std::endl;
        return 1;
    }

    return 0;
}