#include <fstream>
#include <iostream>

#include "Compiler.hpp"
#include "Error.hpp"
#include "FunctionObject.hpp"
#include "Lexer.hpp"
#include "Parser.hpp"
#include "Util.hpp"
#include "VM.hpp"

int main() {
    std::string sourceCode;

    std::ifstream fStream("fixtures/test.ei");

    std::string t;
    while (std::getline(fStream, t)) sourceCode += t += '\n';

    try {
        EigerC::Lexer lex(sourceCode);
        EigerC::Parser parser(lex);

        EigerC::CompilerContext ctx;
        std::shared_ptr<EigerC::Scope> globalScope =
            std::make_shared<EigerC::Scope>(ctx);

        // Builtin Func Declarations
        // TODO: move this
        int emitlnID = ctx.GetVariableID("emitln");
        auto emitlnConst = ctx.AddConstant(std::make_shared<EigerC::Emitln>());
        globalScope->DeclareVar(emitlnID);
        globalScope->SetVar(emitlnID, ctx.constantsTable[0], 0);
        //

        std::unique_ptr<EigerC::ScopeNode> root = parser.Parse();

        root->PrettyPrint();

        EigerC::BytecodeCompiler compiler(std::move(root), ctx);
        compiler.DoCodegen();

        std::cout << "==== Generated Bytecode ====" << std::endl;
        for (const EigerC::Instruction& inst : compiler.GetInstructions())
            inst.PrettyPrint();
        std::cout << "====                    ====" << std::endl;

        std::cout << "====      VM Result     ====" << std::endl;

        EigerC::BytecodeVM vm(compiler.GetInstructions(), ctx, globalScope);

        vm.ExecuteBytecode();

    } catch (EigerC::Error& e) {
        std::cerr << EigerC::Util::ErrorTypeToString(e.GetType()) << ": "
                  << e.GetMessage() << " at line " << e.GetLine() << std::endl;
        return 1;
    } catch (const std::exception& e) {
        std::cerr << "Unexpected error: " << e.what() << std::endl;
        return 1;
    }

    return 0;
}