#include <fstream>
#include <iostream>
#include <memory>

#include "Compiler.hpp"
#include "Context.hpp"
#include "Error.hpp"
#include "FunctionObject.hpp"
#include "Lexer.hpp"
#include "Parser.hpp"
#include "Scope.hpp"
#include "Util.hpp"
#include "VM.hpp"

int RunSource(const std::string& src, EigerC::CompilerContext& ctx,
              std::shared_ptr<EigerC::Scope> globalScope,
              bool verbose = false) {
    try {
        EigerC::Lexer lex(src);
        EigerC::Parser parser(lex);

        // Builtin Func Declarations
        // TODO: move this
        int emitlnID = ctx.GetVariableID("emitln");
        auto emitlnConst = ctx.AddConstant(std::make_shared<EigerC::Emitln>());
        globalScope->DeclareVar(emitlnID);
        globalScope->SetVar(emitlnID, ctx.constantsTable[0], 0);
        //

        std::unique_ptr<EigerC::ScopeNode> root = parser.Parse();

        if (verbose) root->PrettyPrint();

        EigerC::BytecodeCompiler compiler(std::move(root), ctx);
        compiler.DoCodegen();

        if (verbose) {
            std::cout << "==== Generated Bytecode ====" << std::endl;
            for (const EigerC::Instruction& inst : compiler.GetInstructions())
                inst.PrettyPrint();
            std::cout << "====                    ====" << std::endl;

            std::cout << "====      VM Result     ====" << std::endl;
        }

        EigerC::BytecodeVM vm(compiler.GetInstructions(), ctx, globalScope);

        vm.ExecuteBytecode();

        return 0;
    } catch (EigerC::Error& e) {
        std::cerr << EigerC::Util::ErrorTypeToString(e.GetType()) << ": "
                  << e.GetMessage() << " at line " << e.GetLine() << std::endl;
        return 1;
    }
}

int RunFile(const std::string& filepath) {
    std::string sourceCode;
    std::ifstream fStream(filepath);

    EigerC::CompilerContext ctx;
    std::shared_ptr<EigerC::Scope> globalScope =
        std::make_shared<EigerC::Scope>(ctx);

    std::string l;
    while (std::getline(fStream, l)) sourceCode += l += '\n';

    return RunSource(sourceCode, ctx, globalScope);
}

void RunShell() {
    EigerC::CompilerContext ctx;
    std::shared_ptr<EigerC::Scope> globalScope =
        std::make_shared<EigerC::Scope>(ctx);

    while (true) {
        std::string sourceCode;
        std::getline(std::cin, sourceCode);
        RunSource(sourceCode, ctx, globalScope);
    }
}

int main() {
    try {
        // int t = RunFile("fixtures/test.ei");
        // if (t) return t;
        RunShell();
    } catch (const std::exception& e) {
        std::cerr << "Unexpected error: " << e.what() << std::endl;
        return 1;
    }

    return 0;
}
